### ISSUE TITLE
Use notbit as bitmessage engine

### ISSUE THREAD

**Issue by olext** [813492291816/BitChan#4]
Can the project use notbit as internal engine instead of docker with bitmessage? 
Ref https://github.com/bpeel/notbit

**Comment by 813492291816** [comment]
From https://github.com/bpeel/notbit/blob/ecaa3e6d8a121d198cebc0ffe8e39386bd914d07/README.md#intro:

>Notbit... doesn't yet support channels

Which is what BitChan uses for lists and boards.
