### ISSUE TITLE
Denied pull

### ISSUE THREAD

**Issue by krionical** [813492291816/BitChan#5]
Arch derivative gives the following error:

 sudo docker-compose up --build -d                                                                      1 ✘  11.10.1  
[+] Running 0/2
 ⠿ bitchan_daemon Error                                                                                                                                    5.5s
 ⠿ bitchan_flask Error                                                                                                                                     5.5s
Error response from daemon: pull access denied for app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by 813492291816** [comment]
appears to be a network issue, not permission
